[workspace]

members = [
	"sdl_02_get_an_image_on_the_screen",
	"sdl_03_event_driving_programming",
	"sdl_04_key_presses",
	"sdl_08_geometry_rendering",
	"sdl_09_viewport",
	"sdl_10_color_keying",
	"sdl_13_alpha_blending",
	"sdl_23_advanced_timers",
	"sdl_24_calculating_frame_rate",
]
